### ISSUE TITLE
asis not defined

### ISSUE THREAD

**Issue by kkellersnow** [emmett-framework/renoir#4]
I want to use a string that contains html and use it unescaped in my template. 

I thought I could use asis inside renoir for it but it does not work: 

Template: 

<html lang="en">
<head>
    <title>My Webpage</title>
</head>
<body>
     {{ =asis(message) }}
</body>
</html>

error:

  File "/Users/kkeller/Development/websaw_upytl/websaw/example.html", line 6, in template
    {{ =asis(message) }}
NameError: name 'asis' is not defined

Could you help me? 

Thanks!

**Comment by gi0baro** [comment]
Hi @kkellersnow, the `asis` function is implemented in `emmett`, but you can easily re-implement what it does, see this https://github.com/emmett-framework/renoir/issues/2#issuecomment-952639033
